version: '2'

services:
  web:
    build: ./app
    command: python manage.py runserver 0.0.0.0:8100
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8100:8100
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      # To persist the data beyond the life of the container 
      # we configured a volume. This config will bind postgres_data 
      # to the "/var/lib/postgresql/data/" 
      # directory in the container.
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=hello_django
      - POSTGRES_PASSWORD=hello_django
      - POSTGRES_DB=hello_django_dev
  adminer:
    image: adminer
    ports:
      - 8200:8080

volumes:
  postgres_data:
